### ISSUE TITLE
If the question is asked too many times it returns the question

### ISSUE THREAD

**Issue by AndrewGuadi** [daveshap/PineconeInfiniteMemoryChatbot#2]
When using this method to retrieve data using cosine similarity form pinecone, if the question has been asked the same amount of times as the converstion_length variable (currently set to 30) then it will retrieve the 30 most similar entries, which all will be the exact question if asked in the same manner. 

Would it be better to incorporate a memory retrieval function using something like tensorFlow? or would it be better to retrieve "memories" that surround those that are most similar depending on the input?

Would love to hop on this project with you.

**Comment by daveshap** [comment]
Jump over to RAVEN! https://github.com/daveshap/raven
